name: kostkontrakanmod5
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Kebutuhan Modul 3 (Sudah Ada)
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.2.0
  dio: ^5.4.0

  # Kebutuhan Baru Modul 4 & 5
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^2.5.0
  path_provider: ^2.1.3
  geolocator: ^13.0.1
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  intl: ^0.19.0

  # Tambahan Modul 6
  firebase_core: ^3.15.2  # Sesuaikan versi terbaru/stabil
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true